apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sehaj07/myapp:b181b3a6f9bd9c2e9186dd26cd93a6c802c2132e
        ports:
        - containerPort: 3000
